package vc.rux.codingtest.hangman.repository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class WordsRepository {
    public String getRandomWord() {
        return words[(int)(Math.random()*10000) % words.length];
    }

    private static final String[] words = new String[] {
            "angels",
            "announcement",
            "bells",
            "bethlehem",
            "blitzen",
            "candles",
            "candy",
            "candy canes",
            "cards",
            "advent",
            "cedar",
            "celebrate",
            "ceremonies",
            "chimney",
            "christmas cookies",
            "christmas tree",
            "cold",
            "comet",
            "cranberry sauce",
            "crowds",
            "cupid",
            "dancer",
            "dasher",
            "december",
            "decorations",
            "dolls",
            "donner",
            "dressing",
            "eggnog",
            "elves",
            "family reunion",
            "festival",
            "fir",
            "frosty",
            "fruitcake",
            "gift boxes",
            "gifts",
            "goodwill",
            "greetings",
            "ham",
            "happy",
            "holiday",
            "holly",
            "holy",
            "icicles",
            "jolly",
            "lights",
            "lists",
            "merry",
            "miracle",
            "mistletoe",
            "new year",
            "noel",
            "north pole",
            "pageant",
            "parades",
            "party",
            "pie",
            "pine",
            "plum pudding",
            "poinsettia",
            "prancer",
            "presents",
            "pumpkin pie",
            "punch",
            "red/green",
            "reindeer",
            "ribbon",
            "rudolph",
            "sacred",
            "sales",
            "sauce",
            "scrooge",
            "season",
            "sled",
            "sleigh bells",
            "snowflakes",
            "spirit",
            "stand",
            "star",
            "stickers",
            "stocking stuffers",
            "sweet potato",
            "tidings",
            "tinsel",
            "togetherness",
            "toys",
            "tradition",
            "traffic",
            "trips",
            "turkey",
            "vacation",
            "vixen",
            "winter",
            "worship",
            "wrapping paper",
            "wreath",
            "yule",
            "yuletide"
    };
}
